#!/usr/bin/perl

sub usage {
	die "incbin.pl in.bin symbol\n";
}

my $in = shift @ARGV or usage();
my $symbol = shift @ARGV or usage();

open IN, "$in" or die "$in: $!\n";
binmode(IN);
print "// generated by incbin.pl from $in\n";
print "const unsigned char ${symbol}[] = {\n";
my $i = 0;
while (read(IN, my $byte, 1)) {
	print "\t" if ($i == 0);
	printf "0x%02x", (unpack 'C', $byte);
	print "," unless eof IN;
	$i++;
	if ($i == 16) {
		$i = 0;
		print "\n";
	}
}
print "\n};\n\n";
print "const int ${symbol}_size = (int)sizeof($symbol);";
close IN;
